name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  SPM:
    name: "Tests via SPM"
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: set -o pipefail && swift test

